In [1]:
import numpy as np

def relu(z):
    return np.maximum(0, z)

def relu_derivative(z):
    return (z > 0).astype(float)

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def sigmoid_derivative(z):
    s = sigmoid(z)
    return s * (1 - s)

def mse(y, y_hat): return np.mean((y - y_hat) ** 2)



In [2]:
def train_with_fixed_weights(X, Y, epochs=50):
    W1 = np.array([
        [0.1, -0.2],
        [0.4, 0.3],
        [-0.5, 0.2]
    ])
    W2 = np.array([
        [0.3, -0.4, 0.1]
    ])

    for epoch in range(epochs):
        Z1 = W1 @ X
        A1 = relu(Z1)
        Z2 = W2 @ A1
        A2 = sigmoid(Z2)

        loss = mse(Y, A2)

        if epoch%5 == 0:
            print(f"Epoch {epoch}, MSE: {loss:.6f}")

        if loss != 0 and epoch % 5 == 0:
            dZ2 = 2 * (A2 - Y) * sigmoid_derivative(Z2)
            dW2 = dZ2 @ A1.T / X.shape[1]

            dZ1 = (W2.T @ dZ2) * relu_derivative(Z1)
            dW1 = dZ1 @ X.T / X.shape[1]

            W1 -= dW1
            W2 -= dW2

            print("Updated W1:\n", W1)
            print("Updated W2:\n", W2)

X = np.array([[0, 0, 1, 1],
              [0, 1, 0, 1]])
Y = np.array([[0, 1, 1, 0]])

train_with_fixed_weights(X, Y)

Epoch 0, MSE: 0.248600
Updated W1:
 [[ 0.11988291 -0.2       ]
 [ 0.39459575  0.29492285]
 [-0.5         0.20654586]]
Updated W2:
 [[ 0.30662764 -0.39078788  0.11309172]]
Epoch 5, MSE: 0.247799
Updated W1:
 [[ 0.14010141 -0.2       ]
 [ 0.38960188  0.29020505]
 [-0.5         0.21392304]]
Updated W2:
 [[ 0.31453251 -0.3821849   0.12656509]]
Epoch 10, MSE: 0.246959
Updated W1:
 [[ 0.16073244 -0.2       ]
 [ 0.38498713  0.28581525]
 [-0.5         0.22215029]]
Updated W2:
 [[ 0.32372214 -0.37414727  0.14047096]]
Epoch 15, MSE: 0.246069
Updated W1:
 [[ 0.18185048 -0.2       ]
 [ 0.38072572  0.28172689]
 [-0.5         0.23124895]]
Updated W2:
 [[ 0.33420753 -0.36663925  0.1548602 ]]
Epoch 20, MSE: 0.245114
Updated W1:
 [[ 0.20352747 -0.2       ]
 [ 0.37679672  0.27791756]
 [-0.5         0.24124278]]
Updated W2:
 [[ 0.34600251 -0.35963219  0.16978374]]
Epoch 25, MSE: 0.244149
Updated W1:
 [[ 0.20698819 -0.21884432]
 [ 0.37319967  0.27438454]
 [-0.5         0.25215765]]
Updated W2:
 [[ 0.35893