In [ ]:
import numpy as np


Input

In [2]:
X=np.array([[0,0,1,1],[0,1,0,1]])
print(f'{X.shape=}')
X

X.shape=(2, 4)


array([[0, 0, 1, 1],
       [0, 1, 0, 1]])

In [5]:
t=np.array([[0,0,0,1]])
print(f'{t.shape=}')
t

t.shape=(1, 4)


array([[0, 0, 0, 1]])

Add bias

In [6]:
A=np.vstack((np.ones((1,4)),X))
A

array([[1., 1., 1., 1.],
       [0., 0., 1., 1.],
       [0., 1., 0., 1.]])

Initialize Weights

In [7]:
W=np.array([[0,0,0]])
print(f'{W.shape=}')

W.shape=(1, 3)


In [8]:
MAX_EPOCH = 10

Perceptron Learning

In [11]:
for ep in range(MAX_EPOCH):
    print('Epoch-', ep+1 , '='*50)
    isConv = True
    for x,y in zip(A.T, t.ravel()):
        Z= W @ x.T
        #Actually from positive but predicted as negative
        if y>0 and Z < 0:
            W=W+x
            isConv = False
            print('Update: W+x')
        #Actually from negative but predicted as positive 
        if y<1 and Z>=0:
            W=W-x
            isConv = False
            print('Update: W-x')
        print(x,y,Z,W)
    if isConv:
        print('Final weights:' , W)
        break

Epoch- 1 ==================================================
Update: W-x
[1. 0. 0.] 0 [0.] [[-1.  0.  0.]]
[1. 0. 1.] 0 [-1.] [[-1.  0.  0.]]
[1. 1. 0.] 0 [-1.] [[-1.  0.  0.]]
Update: W+x
[1. 1. 1.] 1 [-1.] [[0. 1. 1.]]
Epoch- 2 ==================================================
Update: W-x
[1. 0. 0.] 0 [0.] [[-1.  1.  1.]]
Update: W-x
[1. 0. 1.] 0 [0.] [[-2.  1.  0.]]
[1. 1. 0.] 0 [-1.] [[-2.  1.  0.]]
Update: W+x
[1. 1. 1.] 1 [-1.] [[-1.  2.  1.]]
Epoch- 3 ==================================================
[1. 0. 0.] 0 [-1.] [[-1.  2.  1.]]
Update: W-x
[1. 0. 1.] 0 [0.] [[-2.  2.  0.]]
Update: W-x
[1. 1. 0.] 0 [0.] [[-3.  1.  0.]]
Update: W+x
[1. 1. 1.] 1 [-2.] [[-2.  2.  1.]]
Epoch- 4 ==================================================
[1. 0. 0.] 0 [-2.] [[-2.  2.  1.]]
[1. 0. 1.] 0 [-1.] [[-2.  2.  1.]]
Update: W-x
[1. 1. 0.] 0 [0.] [[-3.  1.  1.]]
Update: W+x
[1. 1. 1.] 1 [-1.] [[-2.  2.  2.]]
Epoch- 5 ==================================================
[1. 0. 0.] 0 [-2.] [[-2.  2. 

In [12]:
Z = W @ A
y_pred = [int(pred >=0) for pred in Z.ravel()]
print(f'{y_pred=}')

y_pred=[0, 0, 0, 1]
